v4l2-ctl -d /dev/video1 --set-ctrl=brightness=0
v4l2-ctl -d /dev/video1 --set-ctrl=contrast=30
v4l2-ctl -d /dev/video1 --set-ctrl=saturation=30
v4l2-ctl -d /dev/video1 --set-ctrl=hue=1900
v4l2-ctl -d /dev/video1 --set-ctrl=white_balance_temperature_auto=0
#v4l2-ctl -d /dev/video1 --set-ctrl=gain=0
#v4l2-ctl -d /dev/video1 --set-ctrl=power_line_frequency=2
v4l2-ctl -d /dev/video1 --set-ctrl=white_balance_temperature=4100
v4l2-ctl -d /dev/video1 --set-ctrl=sharpness=5
#v4l2-ctl -d /dev/video1 --set-ctrl=backlight_compensation=0
v4l2-ctl -d /dev/video1 --set-ctrl=exposure_auto=1
v4l2-ctl -d /dev/video1 --set-ctrl=exposure_absolute=240
#v4l2-ctl -d /dev/video1 --set-ctrl=exposure_auto_priority=0
#v4l2-ctl -d /dev/video1 --set-ctrl=pan_absolute=0
#v4l2-ctl -d /dev/video1 --set-ctrl=tilt_absolute=0
#v4l2-ctl -d /dev/video1 --set-ctrl=focus_auto=0
#v4l2-ctl -d /dev/video1 --set-ctrl=focus_absolute=0
#v4l2-ctl -d /dev/video1 --set-ctrl=zoom_absolute=100

v4l2-ctl -d /dev/video1 --list-ctrls
